name: Rust

on: "push"
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build
        run: cargo build
      - name: rust-tarpaulin
        uses: actions-rs/tarpaulin@v0.1.0
        with:
          version: "0.27.3"
          args: '-- --test-threads 1'
